### ISSUE TITLE
Feb 5 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#10]
- [x] fig resizing to make circles be circles
- [x] shorten links to other manip vars
- [x] links to other man tours htmls, maybe an overview page that lists all the animations for the paper, and each has a link back to this page
- [x] timeline, clarify titles, match to chapters, and parts of chapters text-wise
- [x] chapters 4, 5 paragraph structure cleanup
- [x] list three research objectives in the introduction
- [x] write abstract
