### ISSUE TITLE
Feb 11 TODO, w/ kim

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#12]
- [x] Lit review of VR needs segue to questions
- [x] Lit review of VR include images of other papers
- [x] Lit review explain depth cues
- [x] research questions should be expanded on and research methodology listed intro section
- [x] in RO B, explain PCA, LDA, tSNE
- [x] change inter-operability terminology to transparency/opacity
- [x] make sure that work RO B:D, are listed as future work, 
- [x] preface spinifex chapter as previous work, to be published to R journal
- [x] in timeline include journal, R, VAST, CHI, VAST? respectively?
