### ISSUE TITLE
Feb 12 TODO

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#13]
- [x] lit review, change header of touring to something more descriptive.
- [x] point out the gap in the literature, and segue into RO.
- [x] remove "for the sake of" statements. phrase more as because x then staying focused
- [x] 2d, 3d consistency 

key feature for going back to 3d, it that it's more accessible now
