### ISSUE TITLE
Feb21 TODO

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#14]
Meeting with Kim and Di 21/02/2019 -- candidature confirmation postponed
__
- [x] research question back to introduction and motivation
- [x] tour lit more through explanation with diagrams
- [x] less head on, more gentle introductions
- [x] need to explain tour and usc
- [x] human in the loop data analytics
- [x] tool, R agnostic.
- [x] Lit review: higher level motivation. (research questions as is for now, possibly split out in Lit review later)
--more motivation as to why 3D, and what we can gain from it.
- [x] Spinifex paper as appendix: work completed so far.
- [x] Spinifex chap, higher level in 5-6 pages, *completed so far*
- [x] Collapse chap 3-5 to 1 chapter, *future work*

Zoom meetings Friday 10am.

Confirmation reschedule:
-3/4 weeks out
-Kim teaching: tues/wedn
-Di teaching: thur
