### ISSUE TITLE
Feb 28  TODO - Julie Holden

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#15]
- [x] explicit listing of methodology (delineate from RO's)
--need fleshing out
- [x] insert RO's  rmd syntax
- [cut] explicit list of problem statement
--need fleshing out
- [x] explicit list of contribution statement
--need fleshing out
- [x] one page overview of project (flow chart)
- [x] word level changes, 12x on hard copy
- [x] schedule sectioning_ns
###
general themes to extend about research proposal:
- Valid (Why)
- Feasible (How)
