### ISSUE TITLE
TODO 1/3/2019

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#16]
- [x] bullet point out objectives
- [x] add paragraph to start of lit review
- [x] introduction chapter needs a "research methodology" section that has
- [x] 1. data analysis workflow and reproducible principles
- [x] 2. experimental design for human studies, including evaluating "best" (you can also reference hofmann, follett, cook "comparing designs" IEEE InfoVis paper which uses visual inference for assessing power of a particular design
- [x] Shift the big blocks of terminology and notation into a "Glossary" in the appendix. Put small parts as necessary near where it is used.
- [x] Remove duplicated material between Chapter "Completed Work" and "Appendix"
- [x] Be clearer on the steps needed in the future work parts
