### ISSUE TITLE
March 8 TODO 

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#17]
- [x] Di's emailed comments
- [x] pdf comments from the last meeting
- [x] pdf comments from Kim
- [x] Grammarly check
- [x] meeting with Julie setup
- [x] cut a few images from the second part of the lit review.
