### ISSUE TITLE
Mar 14 TODO Meeting 2 with Julie

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#18]
- [x] word level proofread
- [x] contribution section (intro), before methodology.
- [x] soft copy changes
- [x] hard copy changes

**Comment by nspyrison** [comment]
- [x] reference and citation matching + cleanup
