### ISSUE TITLE
 Jan 2 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#2]
- [x] Clean up package details, as noted
- [x] Write framework for manual tour chapter - sketch out the key parts to the paper, and write up the algorithm
- [ ] Shiny GUI for manual tour
