### ISSUE TITLE
Jan 22 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#5]
- [x] figure captions: 
Figure captions should have three components: (1) what is the plot about, (2) specific details of plot, like what type of display and how variables are mapped, (3) the most important thing that the reader should learn.
- [x] small informative code blocks
- [x] figure reference/labels
- [x] Make discussion full sentences and paragraphs
- [x] Links should be informative, not generic vague like "Github page"
- [x] Fig 3.1 also add data plots for each step
