### ISSUE TITLE
Jan 18 TODO

### ISSUE THREAD

**Issue by nspyrison** [nspyrison/thesis_monash_phd#6]
Diagrams for step on chap3, spinifex.

Combine, the math, code, and above diagrams inline in the manual tour section:
- [x] step 1 
- [x] step 2
- [x] step 3

Application section (previously Usage):
- [x] Stand up blogdown website
- [x] HTML outputs to a link going to link on my website
- [x] recreate Ursula's PDFsense data from first figure
- [x] manual rotation on the PDF sense data.
