### ISSUE TITLE
Jan 25 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#7]
- [x] Paragraph for each of the physics animations summarising what was said in ursula's paper
- [x] Sequence of stills to explain what can be learned about contribution of variables to structure: two manip vars for each example, one where variable doesn't contribute and the other where it does
- [x] Break out the 2 links of html animation into 4, showing each of the above.
- [x] Variable axis display to bottom left, so it is visible
- [x] remove legend for the flea example
- [x] use variable names in the ggplot2 code of spinifex, and find another way to satisfy global variables complaint from CRAN
- [x] the projection shown in Fig 3.1 is not the projection starting the manual tour in Fig 3.3. I think Fig 3 needs to be changed to be the same.

**Comment by nspyrison** [comment]
- [x] change manual_tour() to create "history_array" like tourr:save_history
- [x] change array2df() to work off "history_array"
- [x] change play_manual_tour() and play_tour_path() to include interpolate() and angle
- [x] check() changes
