### ISSUE TITLE
Jan 29 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#8]
- [x] Fig 3.3 needs to be resized to make circles
-- same settings as similar figs; subject to float pagination, should take full page with caption
- [x] Check spelling - always needs to be done before meetings
- [x] Principal not principle for PCA - always check yourself on this
- [x] Animations for all PCs in the example section.
- [ ] Complete the previous TODOs
-- [ ] shiny app for manual tours
- [x] General (thesis) polish, complete chapter 3, and revise headings of other chapters
- [x] Interpolation function fix?
