### ISSUE TITLE
Feb 1 TODO

### ISSUE THREAD

**Issue by dicook** [nspyrison/thesis_monash_phd#9]
- [x] Colour of points for figure 3.1 needs to match other figures
- [x] Figure 3.4 data not showing
- [x] Discuss topics for remaining chapters with Kim
- [x] Add timeline section

**Comment by nspyrison** [comment]
- [x] plotly text not working reliably
-- [ ] hack for geom_text contention, but had to allow tooltips to show.
- [x] netlify not pushing even with basis hardcoded, "unmarshal" format error.
-- csv, dataframe.rda don't work, googled, asking around.
